# Generated by Django 2.1.5 on 2022-01-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item_category',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_categoryname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='item category'),
            preserve_default=False,
        ),
    ]
