# Generated by Django 2.1.5 on 2022-02-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_inventory_item_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='category',
        ),
    ]
