# Generated by Django 2.1.5 on 2022-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_shopproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='parenttel',
            field=models.CharField(default=2348144671045, max_length=13, verbose_name='Parent Telephone Number(Whatsapp)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product_price1',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
