# Generated by Django 2.1.5 on 2022-02-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220215_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='receipt',
        ),
    ]
