# Generated by Django 2.1.5 on 2022-02-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220215_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
